# Generated by Django 5.2.13 on 2026-04-27 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workingday'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='core.academicperiod')),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_offerings', to='core.academicprogram')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='core.subject')),
            ],
            options={
                'ordering': ['academic_period', 'semester', 'subject__code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('semester__gte', 1)), name='subject_offering_valid_semester'), models.UniqueConstraint(fields=('academic_period', 'subject', 'academic_program', 'semester'), name='unique_subject_offering_per_period_program_semester')],
            },
        ),
    ]
